import { Article, NewsItem, VideoItem } from "@/types/content";

export const mockArticles: Article[] = [
  {
    id: "art001",
    title: "10 thói quen giúp duy trì sức khỏe tim mạch tốt",
    slug: "10-thoi-quen-suc-khoe-tim-mach",
    excerpt: "Tim mạch khỏe mạnh là nền tảng của cuộc sống lâu dài. Hãy cùng tìm hiểu những thói quen đơn giản nhưng hiệu quả.",
    content: "<p>Nội dung bài viết chi tiết về 10 thói quen tim mạch...</p>",
    coverImageUrl: "/images/articles/art001.jpg",
    categoryId: "cat001",
    categoryName: "Tim mạch",
    tags: ["tim mạch", "sức khỏe", "lối sống"],
    authorId: "d002",
    authorName: "BS. Lê Thị Bích",
    status: "published",
    isFeatured: true,
    viewCount: 1250,
    publishedAt: "2024-06-01T08:00:00Z",
    createdAt: "2024-05-28T10:00:00Z",
    updatedAt: "2024-06-01T07:30:00Z",
  },
  {
    id: "art002",
    title: "Hướng dẫn chăm sóc sức khỏe thai kỳ từng tháng",
    slug: "cham-soc-suc-khoe-thai-ky",
    excerpt: "Chuẩn bị tốt cho thai kỳ là điều quan trọng nhất mà mọi bà mẹ cần làm. Bài viết chia sẻ chi tiết từng giai đoạn.",
    content: "<p>Nội dung chi tiết theo từng tháng thai kỳ...</p>",
    coverImageUrl: "/images/articles/art002.jpg",
    categoryId: "cat002",
    categoryName: "Sản phụ khoa",
    tags: ["thai kỳ", "sản phụ khoa"],
    authorId: "d003",
    authorName: "BS. Nguyễn Minh Tuấn",
    status: "published",
    isFeatured: false,
    viewCount: 3400,
    publishedAt: "2024-06-15T09:00:00Z",
    createdAt: "2024-06-12T14:00:00Z",
    updatedAt: "2024-06-15T08:00:00Z",
  },
  { id: "art003", title: "Phòng ngừa tiểu đường tuýp 2: Những điều cần biết", slug: "phong-ngua-tieu-duong-tuyp-2", excerpt: "Tiểu đường tuýp 2 có thể phòng ngừa được nếu bạn thay đổi lối sống đúng cách.", content: "<p>Nội dung chi tiết về phòng ngừa tiểu đường...</p>", coverImageUrl: "/images/articles/art003.jpg", categoryId: "cat003", categoryName: "Nội tiết", tags: ["tiểu đường", "nội tiết", "dinh dưỡng"], authorId: "d001", authorName: "BS. Trần Văn An", status: "published", isFeatured: true, viewCount: 2100, publishedAt: "2024-07-05T08:00:00Z", createdAt: "2024-07-02T10:00:00Z", updatedAt: "2024-07-05T07:00:00Z" },
  { id: "art004", title: "Trẻ em và bệnh sốt xuất huyết: Cách nhận biết và xử lý", slug: "tre-em-sot-xuat-huyet", excerpt: "Sốt xuất huyết ở trẻ em cần được phát hiện sớm và điều trị kịp thời để tránh biến chứng nguy hiểm.", content: "<p>Hướng dẫn nhận biết và xử trí sốt xuất huyết ở trẻ...</p>", coverImageUrl: "/images/articles/art004.jpg", categoryId: "cat004", categoryName: "Nhi khoa", tags: ["nhi khoa", "sốt xuất huyết", "trẻ em"], authorId: "d004", authorName: "BS. Phạm Thành Long", status: "published", isFeatured: false, viewCount: 5800, publishedAt: "2024-08-01T09:00:00Z", createdAt: "2024-07-29T14:00:00Z", updatedAt: "2024-08-01T08:00:00Z" },
  { id: "art005", title: "Chăm sóc da mùa hè: Lời khuyên từ chuyên gia da liễu", slug: "cham-soc-da-mua-he", excerpt: "Mùa hè khắc nghiệt ảnh hưởng nhiều đến làn da. Các bước chăm sóc đúng cách giúp da khỏe mạnh suốt mùa hè.", content: "<p>Tips chăm sóc da mùa hè từ chuyên gia...</p>", coverImageUrl: "/images/articles/art005.jpg", categoryId: "cat007", categoryName: "Da liễu", tags: ["da liễu", "chăm sóc da"], authorId: "d001", authorName: "BS. Trần Văn An", status: "draft", isFeatured: false, viewCount: 0, createdAt: "2024-08-10T10:00:00Z", updatedAt: "2024-08-10T10:00:00Z" },
  { id: "art006", title: "Loãng xương: Nguyên nhân và phòng ngừa hiệu quả", slug: "loang-xuong-nguyen-nhan-phong-ngua", excerpt: "Loãng xương là căn bệnh âm thầm ảnh hưởng nhiều đến người cao tuổi. Phòng ngừa sớm là chìa khóa quan trọng.", content: "<p>Chi tiết về loãng xương và biện pháp phòng ngừa...</p>", coverImageUrl: "/images/articles/art006.jpg", categoryId: "cat006", categoryName: "Xương khớp", tags: ["xương khớp", "loãng xương", "người cao tuổi"], authorId: "d006", authorName: "BS. Đặng Xuân Hòa", status: "published", isFeatured: false, viewCount: 1900, publishedAt: "2024-08-15T08:00:00Z", createdAt: "2024-08-12T14:00:00Z", updatedAt: "2024-08-15T07:00:00Z" },
];

export const mockNews: NewsItem[] = [
  {
    id: "n001",
    title: "Bệnh viện Bệnh Viện Vạn Hạnh khai trương cơ sở 2 tại Quận 7",
    slug: "khai-truong-co-so-2-quan-7",
    excerpt: "Sáng ngày 1 tháng 7 năm 2024, bệnh viện Bệnh Viện Vạn Hạnh chính thức khai trương cơ sở 2 tại Quận 7.",
    content: "<p>Chi tiết sự kiện khai trương...</p>",
    coverImageUrl: "/images/news/n001.jpg",
    authorId: "admin001",
    authorName: "Ban truyền thông",
    status: "published",
    isFeatured: true,
    viewCount: 4200,
    publishedAt: "2024-07-01T10:00:00Z",
    createdAt: "2024-06-28T14:00:00Z",
    updatedAt: "2024-07-01T09:00:00Z",
  },
  {
    id: "n002",
    title: "Chương trình khám miễn phí cho người cao tuổi nhân Ngày Gia đình Việt Nam",
    slug: "kham-mien-phi-nguoi-cao-tuoi",
    excerpt: "Từ ngày 28/6 đến 30/6/2024, bệnh viện tổ chức chương trình khám bệnh miễn phí cho người trên 65 tuổi.",
    content: "<p>Chi tiết chương trình khám miễn phí...</p>",
    coverImageUrl: "/images/news/n002.jpg",
    authorId: "admin001",
    authorName: "Ban truyền thông",
    status: "published",
    isFeatured: false,
    viewCount: 2800,
    publishedAt: "2024-06-25T08:00:00Z",
    createdAt: "2024-06-23T10:00:00Z",
    updatedAt: "2024-06-24T15:00:00Z",
  },
  { id: "n003", title: "Bổ sung thêm 5 bác sĩ chuyên khoa từ Bệnh viện Chợ Rẫy", slug: "bo-sung-bac-si-chuyen-khoa", excerpt: "Nhằm nâng cao chất lượng khám chữa bệnh, bệnh viện vừa ký hợp đồng với 5 bác sĩ chuyên khoa từ Bệnh viện Chợ Rẫy.", content: "<p>Chi tiết thông báo bổ sung nhân sự...</p>", coverImageUrl: "/images/news/n003.jpg", authorId: "admin001", authorName: "Ban truyền thông", status: "published", isFeatured: true, viewCount: 3100, publishedAt: "2024-07-15T08:00:00Z", createdAt: "2024-07-13T14:00:00Z", updatedAt: "2024-07-15T07:00:00Z" },
  { id: "n004", title: "Cảnh báo dịch bệnh tay chân miệng tăng cao tháng 8", slug: "canh-bao-dich-tay-chan-mieng", excerpt: "Số ca tay chân miệng tại TP.HCM tăng 40% so với cùng kỳ. Phụ huynh cần chú ý các dấu hiệu và biện pháp phòng ngừa.", content: "<p>Thông tin chi tiết về dịch tay chân miệng...</p>", coverImageUrl: "/images/news/n004.jpg", authorId: "admin001", authorName: "Ban truyền thông", status: "published", isFeatured: false, viewCount: 6200, publishedAt: "2024-08-05T09:00:00Z", createdAt: "2024-08-04T10:00:00Z", updatedAt: "2024-08-05T08:00:00Z" },
];

export const mockVideos: VideoItem[] = [
  {
    id: "vid001",
    title: "Hướng dẫn đặt lịch khám trực tuyến qua ứng dụng",
    description: "Video hướng dẫn từng bước đặt lịch khám qua ứng dụng Bệnh Viện Vạn Hạnh.",
    thumbnailUrl: "/images/videos/vid001-thumb.jpg",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    type: "video",
    viewCount: 5600,
    isPublished: true,
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "vid002",
    title: "BS. Lê Thị Bích chia sẻ về phòng ngừa đột quỵ",
    description: "Chuyên gia tim mạch BS. Lê Thị Bích chia sẻ các dấu hiệu nhận biết và cách phòng ngừa đột quỵ.",
    thumbnailUrl: "/images/videos/vid002-thumb.jpg",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    platform: "youtube",
    type: "video",
    viewCount: 12000,
    isPublished: true,
    createdAt: "2024-06-10T00:00:00Z",
  },
  { id: "vid003", title: "Bài tập phục hồi sau phẫu thuật khớp gối", description: "Hướng dẫn các bài tập vật lý trị liệu giúp phục hồi nhanh sau phẫu thuật khớp gối.", thumbnailUrl: "/images/videos/vid003-thumb.jpg", videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", platform: "youtube", type: "video", viewCount: 3200, isPublished: true, createdAt: "2024-07-01T00:00:00Z" },
  { id: "vid004", title: "Dinh dưỡng cho mẹ bầu 3 tháng đầu thai kỳ", description: "BS. Lưu Thị Kiều chia sẻ những thực phẩm nên và không nên ăn trong 3 tháng đầu thai kỳ.", thumbnailUrl: "/images/videos/vid004-thumb.jpg", videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", platform: "youtube", type: "video", viewCount: 8900, isPublished: true, createdAt: "2024-07-20T00:00:00Z" },
  { id: "vid005", title: "Nhận biết dấu hiệu bệnh tim ở trẻ em", description: "Các triệu chứng cảnh báo bệnh tim bẩm sinh và cách xử lý khẩn cấp cho phụ huynh.", thumbnailUrl: "/images/videos/vid005-thumb.jpg", videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ", platform: "youtube", type: "video", viewCount: 4100, isPublished: false, createdAt: "2024-08-05T00:00:00Z" },
];
