import {
  AdminSpecialty,
  Clinic,
  Doctor,
  ExamArea,
  ExamService,
  ExamTicket,
  NightSyncJob,
  Schedule,
} from "@/types/hospital-admin";

const now = "2026-05-13T08:00:00+07:00";
const systemUser = "super_admin";

export const mockExamAreas: ExamArea[] = [
  {
    id: "area-01",
    name: "Khu khám Nội tổng quát",
    description: "Khu khám chính cho các chuyên khoa nội và tái khám.",
    address: "Tầng 2, Khu A, 781/C1 Lê Hồng Phong, Q.10, TP.HCM",
    internal_id: "001",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "area-02",
    name: "Khu khám Chuyên sâu",
    description: "Khu khám tim mạch, cơ xương khớp và dịch vụ chuyên sâu.",
    address: "Tầng 3, Khu B, 781/C1 Lê Hồng Phong, Q.10, TP.HCM",
    internal_id: "002",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockAdminSpecialties: AdminSpecialty[] = [
  {
    id: "sp-01",
    name: "Nội khoa",
    guide_room: "PK Nội 01",
    booking_note: "Ưu tiên bệnh nhân tái khám buổi sáng.",
    internal_id: "001",
    booking_group: "noi-tong-quat",
    display_priority: 1,
    hide_search: false,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "sp-02",
    name: "Tim mạch",
    guide_room: "PK Tim 02",
    booking_note: "Mang theo toa thuốc và kết quả điện tim cũ nếu có.",
    internal_id: "002",
    booking_group: "tim-mach",
    display_priority: 2,
    hide_search: false,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "sp-03",
    name: "Xương khớp",
    guide_room: "PK Cơ xương khớp 01",
    booking_note: "Ưu tiên bệnh nhân cần chụp X-quang cùng ngày.",
    internal_id: "003",
    booking_group: "xuong-khop",
    display_priority: 3,
    hide_search: false,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockClinics: Clinic[] = [
  {
    id: "clinic-01",
    name: "Phòng khám Nội 01",
    clinic_type: "Khám thường",
    guide_room: "Đi thang máy khu A lên tầng 2, quầy số 3",
    booking_note: "Nhận số từ 6h30.",
    area_id: "area-01",
    internal_id: "0101",
    specialty_fees: [
      { specialty_id: "sp-01", fee: 180000 },
      { specialty_id: "sp-02", fee: 250000 },
    ],
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "clinic-02",
    name: "Phòng khám Tim mạch 02",
    clinic_type: "Khám chuyên khoa",
    guide_room: "Khu B tầng 3, quầy tim mạch",
    booking_note: "Chuẩn bị hồ sơ BHYT nếu đăng ký khám BHYT.",
    area_id: "area-02",
    internal_id: "0102",
    specialty_fees: [{ specialty_id: "sp-02", fee: 320000 }],
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "clinic-03",
    name: "Phòng khám Cơ xương khớp 01",
    clinic_type: "Khám chuyên sâu",
    guide_room: "Khu B tầng 3, cuối hành lang bên trái",
    booking_note: "Có thể đổi sang phòng khác nếu bác sĩ điều động đột xuất.",
    area_id: "area-02",
    internal_id: "0103",
    specialty_fees: [{ specialty_id: "sp-03", fee: 280000 }],
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockDoctorsAdmin: Doctor[] = [
  {
    id: "doc-01",
    name: "BS. Trần Văn An",
    title: "Tiến sĩ, Bác sĩ CKI",
    phone: "0901111111",
    email: "an.tran@vanhanh.vn",
    gender: "male",
    date_of_birth: "1980-04-12",
    booking_note: "Khám nội tổng quát và theo dõi bệnh mạn tính.",
    internal_id: "0001",
    account_status: "active",
    booking_group: "noi-tong-quat",
    display_group: "bac-si-noi",
    show_price: true,
    display_priority: 1,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "doc-02",
    name: "BS. Lê Thị Bích",
    title: "Thạc sĩ, Bác sĩ CKII",
    phone: "0902222222",
    email: "bich.le@vanhanh.vn",
    gender: "female",
    date_of_birth: "1978-10-25",
    booking_note: "Ưu tiên bệnh nhân tim mạch tái khám BHYT.",
    internal_id: "0002",
    account_status: "active",
    booking_group: "tim-mach",
    display_group: "bac-si-tim-mach",
    show_price: true,
    display_priority: 1,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "doc-03",
    name: "BS. Đặng Xuân Hòa",
    title: "Bác sĩ CKII",
    phone: "0903333333",
    email: "hoa.dang@vanhanh.vn",
    gender: "male",
    date_of_birth: "1982-07-08",
    booking_note: "Khám cơ xương khớp và tư vấn phẫu thuật.",
    internal_id: "0003",
    account_status: "on_leave",
    booking_group: "xuong-khop",
    display_group: "bac-si-xuong-khop",
    show_price: false,
    display_priority: 2,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockExamServices: ExamService[] = [
  {
    id: "svc-01",
    name: "Khám Nội tổng quát",
    service_type: "Khám chuyên khoa",
    service_group: "Khám bệnh",
    insurance_visit_type: "BHYT + Dịch vụ",
    service_price: 180000,
    base_price: 220000,
    deposit: 50000,
    booking_note: "Mang theo kết quả xét nghiệm gần nhất nếu có.",
    detail: "Khám, tư vấn và chỉ định cận lâm sàng khi cần.",
    guide_room: "Phòng khám Nội 01",
    internal_id: "0201",
    booking_group: "noi-tong-quat",
    display_group: "dich-vu-kham",
    show_price: true,
    display_priority: 1,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "svc-02",
    name: "Khám Tim mạch chuyên sâu",
    service_type: "Khám chuyên sâu",
    service_group: "Khám bệnh",
    insurance_visit_type: "Dịch vụ",
    service_price: 320000,
    base_price: 350000,
    deposit: 100000,
    booking_note: "Có thể cần điện tim hoặc siêu âm tim.",
    detail: "Khám tim mạch, đo điện tim và tư vấn phác đồ điều trị.",
    guide_room: "Phòng khám Tim mạch 02",
    internal_id: "0202",
    booking_group: "tim-mach",
    display_group: "dich-vu-tim-mach",
    show_price: true,
    display_priority: 2,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "svc-03",
    name: "Khám Cơ xương khớp",
    service_type: "Khám chuyên khoa",
    service_group: "Khám bệnh",
    insurance_visit_type: "BHYT + Dịch vụ",
    service_price: 280000,
    base_price: 300000,
    deposit: 80000,
    booking_note: "Ưu tiên bệnh nhân đã có phim chụp hoặc MRI.",
    detail: "Khám, tư vấn chẩn đoán hình ảnh và hướng dẫn điều trị.",
    guide_room: "Phòng khám Cơ xương khớp 01",
    internal_id: "0203",
    booking_group: "xuong-khop",
    display_group: "dich-vu-xuong-khop",
    show_price: false,
    display_priority: 3,
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: "sch-01",
    specialty_id: "sp-01",
    clinic_id: "clinic-01",
    service_id: "svc-01",
    doctor_id: "doc-01",
    shift: "morning",
    ticket_limit: 30,
    patient_flow: "Khám lẻ",
    booking_group: "noi-tong-quat",
    source: "app",
    status: "active",
    recurrence_type: "weekday",
    work_dates: [],
    weekdays: [1, 3, 5],
    start_time: "07:30",
    slot_duration_minutes: 15,
    insurance_mode: "bhyt_and_service",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "sch-02",
    specialty_id: "sp-02",
    clinic_id: "clinic-02",
    service_id: "svc-02",
    doctor_id: "doc-02",
    shift: "afternoon",
    ticket_limit: 18,
    patient_flow: "Khám theo hẹn",
    booking_group: "tim-mach",
    source: "counter",
    status: "active",
    recurrence_type: "date",
    work_dates: ["2026-05-14", "2026-05-16", "2026-05-20"],
    weekdays: [],
    start_time: "13:00",
    slot_duration_minutes: 20,
    insurance_mode: "service_only",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "sch-03",
    specialty_id: "sp-03",
    clinic_id: "clinic-03",
    service_id: "svc-03",
    doctor_id: "doc-03",
    shift: "morning",
    ticket_limit: 20,
    patient_flow: "Khám kết hợp cận lâm sàng",
    booking_group: "xuong-khop",
    source: "app",
    status: "paused",
    recurrence_type: "date",
    work_dates: ["2026-05-18", "2026-05-19"],
    weekdays: [],
    start_time: "08:00",
    slot_duration_minutes: 20,
    insurance_mode: "bhyt_and_service",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "sch-04",
    specialty_id: "sp-02",
    clinic_id: "clinic-01",
    service_id: "svc-02",
    doctor_id: "doc-02",
    shift: "morning",
    ticket_limit: 10,
    patient_flow: "Khám tăng cường",
    booking_group: "tim-mach",
    source: "app",
    status: "active",
    recurrence_type: "weekday",
    work_dates: [],
    weekdays: [2],
    start_time: "08:30",
    slot_duration_minutes: 25,
    insurance_mode: "bhyt_and_service",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockExamTickets: ExamTicket[] = [
  {
    id: "ticket-01",
    ticket_number: "PK-20260514-001",
    patient_name: "Nguyễn Thị Lan",
    patient_code: "BN000245",
    app_patient_code: "APP-NEW-010",
    specialty_id: "sp-01",
    clinic_id: "clinic-01",
    doctor_id: "doc-01",
    service_id: "svc-01",
    schedule_id: "sch-01",
    exam_date: "2026-05-14",
    booking_group: "noi-tong-quat",
    source: "app",
    status: "booked",
    his_sync_status: "pending",
    booked_clinic_ids: ["clinic-01"],
    primary_clinic_id: "clinic-01",
    note: "App tự tạo mã BN mới, chờ đồng bộ HIS.",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "ticket-02",
    ticket_number: "PK-20260514-002",
    patient_name: "Lê Văn Minh",
    patient_code: "BN000310",
    app_patient_code: "BN000310",
    specialty_id: "sp-02",
    clinic_id: "clinic-02",
    doctor_id: "doc-02",
    service_id: "svc-02",
    schedule_id: "sch-02",
    exam_date: "2026-05-14",
    booking_group: "tim-mach",
    source: "counter",
    status: "confirmed",
    his_sync_status: "synced",
    booked_clinic_ids: ["clinic-02", "clinic-03"],
    primary_clinic_id: "clinic-02",
    note: "Đăng ký 2 phòng khám cùng ngày.",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
  {
    id: "ticket-03",
    ticket_number: "PK-20260514-003",
    patient_name: "Phạm Đức Hoàng",
    patient_code: "BN000455",
    app_patient_code: "BN000455",
    specialty_id: "sp-03",
    clinic_id: "clinic-03",
    doctor_id: "doc-03",
    service_id: "svc-03",
    schedule_id: "sch-03",
    exam_date: "2026-05-18",
    booking_group: "xuong-khop",
    source: "app",
    status: "refunded",
    his_sync_status: "failed",
    booked_clinic_ids: ["clinic-03"],
    primary_clinic_id: "clinic-03",
    note: "Cần báo cáo hoàn tiền cho kế toán.",
    refund_reason: "Bác sĩ nghỉ đột xuất",
    cancel_reason: "Bác sĩ nghỉ đột xuất",
    created_at: now,
    created_by: systemUser,
    updated_at: now,
    updated_by: systemUser,
  },
];

export const mockNightSyncJobs: NightSyncJob[] = [
  {
    id: "sync-23h",
    name: "Đồng bộ phiếu khám ngày hôm sau",
    run_time: "23:00",
    enabled: true,
    last_run_at: "2026-05-12T23:00:00+07:00",
    next_run_at: "2026-05-13T23:00:00+07:00",
  },
];
