import { DoctorReview } from "@/types/review";

export const mockReviews: DoctorReview[] = [
  {
    id: "r001",
    patientId: "p001",
    patientName: "Nguyễn Thị Lan",
    doctorId: "d001",
    doctorName: "BS. Trần Văn An",
    appointmentId: "a001",
    rating: 5,
    attitude: 5,
    expertise: 5,
    waitTime: 4,
    facilities: 5,
    comment: "Bác sĩ rất tận tâm và chuyên nghiệp. Giải thích bệnh tình rõ ràng, dễ hiểu. Rất hài lòng!",
    isApproved: true,
    isVisible: true,
    createdAt: "2024-07-09T14:00:00Z",
    updatedAt: "2024-07-09T14:00:00Z",
  },
  {
    id: "r002",
    patientId: "p003",
    patientName: "Lê Thị Hoa",
    doctorId: "d003",
    doctorName: "BS. Nguyễn Minh Tuấn",
    appointmentId: "a003",
    rating: 4,
    attitude: 5,
    expertise: 4,
    waitTime: 3,
    facilities: 4,
    comment: "Bác sĩ khám kỹ lưỡng nhưng chờ hơi lâu. Nhìn chung rất ổn.",
    isApproved: true,
    isVisible: true,
    createdAt: "2024-07-09T16:00:00Z",
    updatedAt: "2024-07-09T16:00:00Z",
  },
  { id: "r003", patientId: "p004", patientName: "Phạm Hồng Nhung", doctorId: "d002", doctorName: "BS. Lê Thị Bích", appointmentId: "a004", rating: 5, attitude: 5, expertise: 5, waitTime: 5, facilities: 4, comment: "Bác sĩ Bích rất giỏi và nhiệt tình. Tư vấn rất chi tiết, tôi hiểu rõ về tình trạng tim mạch của mình. Sẽ giới thiệu cho bạn bè.", isApproved: true, isVisible: true, createdAt: "2024-07-20T10:00:00Z", updatedAt: "2024-07-20T10:00:00Z" },
  { id: "r004", patientId: "p005", patientName: "Lê Văn Đức", doctorId: "d004", doctorName: "BS. Phạm Thành Long", appointmentId: "a005", rating: 3, attitude: 4, expertise: 4, waitTime: 2, facilities: 3, comment: "Bác sĩ khám ổn nhưng phòng chờ đông quá, chờ gần 1 tiếng mới được vào. Cần cải thiện khâu tổ chức.", isApproved: true, isVisible: true, createdAt: "2024-07-25T09:00:00Z", updatedAt: "2024-07-25T09:00:00Z" },
  { id: "r005", patientId: "p007", patientName: "Đặng Minh Khoa", doctorId: "d006", doctorName: "BS. Đặng Xuân Hòa", appointmentId: "a007", rating: 5, attitude: 5, expertise: 5, waitTime: 4, facilities: 5, comment: "Bác sĩ Hòa rất chuyên sâu về xương khớp. Đã chữa được bệnh đau lưng mãn tính của tôi sau nhiều năm. Cảm ơn BS rất nhiều!", isApproved: false, isVisible: false, createdAt: "2024-08-01T14:00:00Z", updatedAt: "2024-08-01T14:00:00Z" },
  { id: "r006", patientId: "p009", patientName: "Cao Minh Trí", doctorId: "d001", doctorName: "BS. Trần Văn An", appointmentId: "a009", rating: 4, attitude: 4, expertise: 5, waitTime: 4, facilities: 4, comment: "Bác sĩ An chẩn đoán rất chính xác. Hài lòng với kết quả điều trị. Sẽ quay lại tái khám.", isApproved: true, isVisible: true, createdAt: "2024-08-10T11:00:00Z", updatedAt: "2024-08-10T11:00:00Z" },
];
