import { Doctor } from "@/app/(dashboard)/doctors/types";

export const mockDoctors: Doctor[] = [
  {
    id: "d001",
    fullName: "Trần Văn An",
    title: "Tiến sĩ, Bác sĩ CKI",
    specialtyId: "sp001",
    specialtyName: "Nội khoa",
    phone: "0901111111",
    email: "an.tran@vanhanh.vn",
    avatar: "/images/doctors/d001.jpg",
    bio: "Bác sĩ hơn 15 năm kinh nghiệm trong lĩnh vực nội khoa, chuyên về tim mạch và hô hấp. Từng tu nghiệp tại Đại học Tokyo, Nhật Bản. Là tác giả của hơn 20 công trình nghiên cứu trong nước và quốc tế.",
    experience: 15,
    averageRating: 4.8,
    totalReviews: 120,
    isActive: true,
    schedule: [
      { dayOfWeek: 1, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 20 }] },
      { dayOfWeek: 3, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 20 }] },
      { dayOfWeek: 5, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 20 }] },
    ],
    createdAt: "2023-01-10T00:00:00Z",
  },
  {
    id: "d002",
    fullName: "Lê Thị Bích",
    title: "Thạc sĩ, Bác sĩ CKII",
    specialtyId: "sp002",
    specialtyName: "Tim mạch",
    phone: "0902222222",
    email: "bich.le@vanhanh.vn",
    avatar: "/images/doctors/d002.jpg",
    bio: "Chuyên gia tim mạch với hơn 20 năm kinh nghiệm, từng tu nghiệp tại Nhật Bản. Chuyên về điều trị bệnh mạch vành, suy tim và rối loạn nhịp tim. Là Thư ký Hội Tim Mạch TP.HCM.",
    experience: 20,
    averageRating: 4.9,
    totalReviews: 250,
    isActive: true,
    schedule: [
      { dayOfWeek: 2, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 15 }] },
      { dayOfWeek: 4, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 15 }] },
      { dayOfWeek: 6, slots: [{ startTime: "08:00", endTime: "11:00", maxPatients: 10 }] },
    ],
    createdAt: "2023-02-15T00:00:00Z",
  },
  {
    id: "d003",
    fullName: "Nguyễn Minh Tuấn",
    title: "Bác sĩ CKI",
    specialtyId: "sp003",
    specialtyName: "Sản phụ khoa",
    phone: "0903333333",
    email: "tuan.nguyen@vanhanh.vn",
    avatar: "/images/doctors/d003.jpg",
    bio: "Bác sĩ sản phụ khoa giàu kinh nghiệm, chuyên về thai sản và phụ khoa. Đã đỡ đᮧu hơn 3.000 ca sinh. Chuyên gia về phẫu thuật nội soi sản khoa.",
    experience: 10,
    averageRating: 4.7,
    totalReviews: 95,
    isActive: true,
    schedule: [
      { dayOfWeek: 1, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 18 }] },
      { dayOfWeek: 2, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 18 }] },
      { dayOfWeek: 5, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 18 }] },
    ],
    createdAt: "2023-03-01T00:00:00Z",
  },
  {
    id: "d004",
    fullName: "Phạm Thành Long",
    title: "Phó Giáo sư, Tiến sĩ",
    specialtyId: "sp004",
    specialtyName: "Nhi khoa",
    phone: "0904444444",
    email: "long.pham@vanhanh.vn",
    avatar: "/images/doctors/d004.jpg",
    bio: "PGS.TS có hơn 25 năm kinh nghiệm nhi khoa. Nguyên Trưởng khoa Nhi Bệnh viện Nhi Đồng 1. Chuyên về bệnh hô hấp trẻ em và dị ứng.",
    experience: 25,
    averageRating: 4.9,
    totalReviews: 380,
    isActive: true,
    schedule: [
      { dayOfWeek: 1, slots: [{ startTime: "08:00", endTime: "11:00", maxPatients: 15 }] },
      { dayOfWeek: 3, slots: [{ startTime: "08:00", endTime: "11:00", maxPatients: 15 }] },
      { dayOfWeek: 5, slots: [{ startTime: "08:00", endTime: "11:00", maxPatients: 15 }] },
    ],
    createdAt: "2023-04-01T00:00:00Z",
  },
  {
    id: "d005",
    fullName: "Hoàng Thị Diễm",
    title: "Thạc sĩ, Bác sĩ CKI",
    specialtyId: "sp005",
    specialtyName: "Ngoại khoa",
    phone: "0905555555",
    email: "diem.hoang@vanhanh.vn",
    avatar: "/images/doctors/d005.jpg",
    bio: "Chuyên gia ngoại khoa với 12 năm kinh nghiệm. Chuyên về phẫu thuật nội soi đường tiêu hoá, điều trị sỏi mật và cắt ruột thừa nội soi.",
    experience: 12,
    averageRating: 4.6,
    totalReviews: 88,
    isActive: true,
    schedule: [
      { dayOfWeek: 2, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 16 }] },
      { dayOfWeek: 4, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 16 }] },
    ],
    createdAt: "2023-05-10T00:00:00Z",
  },
  {
    id: "d006",
    fullName: "Đặng Xuân Hòa",
    title: "Bác sĩ CKII",
    specialtyId: "sp006",
    specialtyName: "Xương khớp",
    phone: "0906666666",
    email: "hoa.dang@vanhanh.vn",
    avatar: "/images/doctors/d006.jpg",
    bio: "Bác sĩ xương khớp 18 năm kinh nghiệm. Chuyên điều trị viêm khớp dạng thấp, gout, thoái hoá khớp và loãng xương. Đã thực hiện hơn 500 ca phẫu thuật thay khớp.",
    experience: 18,
    averageRating: 4.7,
    totalReviews: 142,
    isActive: true,
    schedule: [
      { dayOfWeek: 1, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 20 }] },
      { dayOfWeek: 4, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 20 }] },
      { dayOfWeek: 6, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 15 }] },
    ],
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "d007",
    fullName: "Vũ Quốc Anh",
    title: "Tiến sĩ, Bác sĩ CKI",
    specialtyId: "sp001",
    specialtyName: "Nội khoa",
    phone: "0907777777",
    email: "anh.vu@vanhanh.vn",
    avatar: "/images/doctors/d007.jpg",
    bio: "Chuyên gia nội khoa tiêu hoá. Chuyên điều trị viêm loét dạ dày, bệnh đại tràng và bệnh gan. Có trình độ cao về nội soi tiêu hoá.",
    experience: 13,
    averageRating: 4.5,
    totalReviews: 76,
    isActive: true,
    schedule: [
      { dayOfWeek: 2, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 20 }] },
      { dayOfWeek: 3, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 20 }] },
    ],
    createdAt: "2023-07-01T00:00:00Z",
  },
  {
    id: "d008",
    fullName: "Lưu Thị Kiều",
    title: "Bác sĩ CKI",
    specialtyId: "sp003",
    specialtyName: "Sản phụ khoa",
    phone: "0908888888",
    email: "kieu.luu@vanhanh.vn",
    avatar: "/images/doctors/d008.jpg",
    bio: "Bác sĩ sản phụ khoa 9 năm kinh nghiệm. Chuyên về siêu âm thai kỳ, tư vấn tiền hôn nhân và chăm sóc thai sản.",
    experience: 9,
    averageRating: 4.6,
    totalReviews: 65,
    isActive: true,
    schedule: [
      { dayOfWeek: 3, slots: [{ startTime: "08:00", endTime: "12:00", maxPatients: 18 }] },
      { dayOfWeek: 5, slots: [{ startTime: "13:00", endTime: "17:00", maxPatients: 18 }] },
      { dayOfWeek: 6, slots: [{ startTime: "08:00", endTime: "11:00", maxPatients: 12 }] },
    ],
    createdAt: "2023-08-15T00:00:00Z",
  },
];
