import { AdminNotification } from "@/types/notification";

export const mockNotifications: AdminNotification[] = [
  {
    id: "notif001",
    title: "Nhắc nhở lịch hẹn ngày mai",
    body: "Bạn có lịch hẹn vào lúc 08:00 ngày mai tại bệnh viện Y Khoa Vạn Hạnh. Vui lòng đến đúng giờ.",
    type: "appointment",
    channels: ["app", "zalo"],
    targetAudience: "specific",
    targetPatientIds: ["p001", "p002"],
    status: "sent",
    sentAt: "2024-07-09T18:00:00Z",
    sentCount: 2,
    failedCount: 0,
    createdBy: "u001",
    createdAt: "2024-07-09T17:30:00Z",
  },
  {
    id: "notif002",
    title: "Chương trình ưu đãi tháng 7",
    body: "Nhân dịp sinh nhật bệnh viện, chúng tôi giảm 20% tất cả dịch vụ khám từ 1/7 - 31/7/2024.",
    type: "marketing",
    channels: ["app", "zalo", "sms"],
    targetAudience: "all",
    scheduledAt: "2024-07-01T07:00:00Z",
    status: "sent",
    sentAt: "2024-07-01T07:00:00Z",
    sentCount: 4500,
    failedCount: 12,
    createdBy: "u001",
    createdAt: "2024-06-28T10:00:00Z",
  },
  {
    id: "notif003",
    title: "Thông báo bài viết mới: Phòng ngừa đột quỵ",
    body: "Bài viết mới từ chuyên gia tim mạch BS. Lê Thị Bích vừa được đăng. Đừng bỏ lỡ!",
    type: "content",
    channels: ["app"],
    targetAudience: "members",
    status: "draft",
    createdBy: "u002",
    createdAt: "2024-07-10T09:00:00Z",
  },
];
